runtime: python37

env_variables:
  # MYSQL_UNIX_SOCKET: "/cloudsql/pedulibicara-352415:us-central1:pedulibicara1"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "ps108"
  MYSQL_DB: "pedulibicara"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "10.83.48.4"

vpc_access_connector:
  name: "projects/PeduliBicara/locations/us-central1/connectors/koneksi-sql"
